dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: decide-fe
  strategy: git
  api_key:
    secure: SgCp7y1G+lrK4o3MLpqQfNPVMH7n+PZQQG3CJJ10lXKMOaTIaf7iPbQQ9fmeDOO/DCGJQOytP898/rV/olMQ6nAfMmRpdIhWHMYgRKnjo58fogg9vLjjpAaZ+MtSOibkPcub445QDQLwufav3D4wSh6P+Pt9fxFNR+iWqQr3LXDDYXnMnff2l6Ayx8HHBzKRzktHmbVp+S/03n7CZDuQRnOnPbKpd5jihjuS57URJ6FCZuHu2c1zlds0LPbCTUr73Lfcmrb/DFZNbxe2TUhWoYp/pLvbPDZ39OI/XdMgEau6XdL90Ohv9DCbtB/MvQl52z6RnOR9aoewt8103SW+tM8149NFAgbZ6UPurb/XxHdj7UZY6E161d11kAWiK7LVEH8gYGf2fx5QtEu8/gwebr54NuV1xUKPRXcbZYV7T6feSQHRJz+HagdIt+fNFeQQmXIy78K6tmmwU+34iUQJTlk9kZxSqIjsvgAB9mW8JWghNBrOjOzqgthtQ6sZy8VpHQUUcJ03Ul3Lzp1fpjd2ZvWtXEifc3M72SUEuI1muMRAjmBwmIUvkFJ8MhOGy1tB9SVotW4q4F4mJjrwQYpBGhcFCFAEh1pvh5UspAn+DYfaNRA81wYGlBWOwKAGdJXgkpxYRug4TGL9wJgIQ/ckaj2A9is54YVEFjNw38FsTx0=
